### ISSUE TITLE
Create a width attribute

### ISSUE THREAD

**Issue by bryanjonker-illinois** [web-illinois/ilw-page-title#1]
In http://localhost:5500/demo/body.html, would like a way to extend the image to both sides. Can we create a `width="full"` attribute that allows the component to break the borders of the current container like Hero does?

**Comment by nhjohnstone** [comment]
@bryanjonker-illinois, I added this but not sure if I completely understand what it should be doing with the different width options. It looks ok in the builder, but let me know if there is more needed here
